name: Update Problems JSON
on:
  workflow_dispatch:  # Permite acionar manualmente (opcional)
  push:
    branches: [ "main" ]  # Pode ser acionado por push (se preferir)

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Atualizar problemas.json via API
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Acessa o secret que você criou
        run: |
          # Script para modificar o JSON (exemplo básico)
          echo '{"titulo":"Exemplo","descricao":"Teste"}' > problemas.json

          # Commit e push das mudanças
          git config --global user.name "Seu Nome"
          git config --global user.email "seu-email@exemplo.com"
          git add problemas.json
          git commit -m "Atualiza problemas.json via GitHub Actions"
          git push
