name: Processar Cadastro
on:
  repository_dispatch:
    types: [cadastro_problema]

jobs:
  processar-cadastro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Instalar jq
        run: sudo apt-get install -y jq

      - name: Atualizar arquivo JSON
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Baixar problemas.json atual
          curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/tiemerson/problema_teste/contents/problemas.json" > file.json

          # Decodificar e atualizar
          content=$(jq -r '.content' file.json | base64 -d)
          sha=$(jq -r '.sha' file.json)
          
          novo_problema=$(jq -n \
            --arg t "${{ github.event.client_payload.titulo }}" \
            --arg d "${{ github.event.client_payload.descricao }}" \
            '{titulo:$t, descricao:$d, data:(now|todate)}')

          updated=$(echo "$content" | jq --argjson novo "$novo_problema" '. += [$novo]')

          # Fazer commit
          echo "$updated" > problemas.json
          git add problemas.json
          git commit -m "Cadastro automático: ${{ github.event.client_payload.titulo }}"
          git push
